/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Footer = {
  _id: string;
  _type: 'footer';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  logo?: ComplexImage;
  mainNav?: Array<
    {
      _key: string;
    } & NavLink
  >;
  secondaryNav?: Array<
    {
      _key: string;
    } & NavLink
  >;
  socials?: Array<
    {
      _key: string;
    } & SocialLink
  >;
};

export type Header = {
  _id: string;
  _type: 'header';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  logo?: ComplexImage;
  nav?: Array<
    {
      _key: string;
    } & NavLink
  >;
  cta?: CtaLink;
};

export type ThemeSettings = {
  _id: string;
  _type: 'themeSettings';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  brandColor?: string;
  textColor?: string;
  backgroundColor?: string;
};

export type SiteSettings = {
  _id: string;
  _type: 'siteSettings';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  metaSettings?: MetaSettings;
  favicon?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  ogVisual?: ComplexImage;
  socials?: Array<
    {
      _key: string;
    } & SocialLink
  >;
  privacyPolicy?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'page';
  };
  imprint?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'page';
  };
  analytics?: AnalyticsSettings;
};

export type PageBuilderComponent = {
  _type: 'pageBuilderComponent';
  title?: string;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'normal' | 'h1' | 'h2' | 'h3';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<
          | ({
              _key: string;
            } & MarkExternalLink)
          | ({
              _key: string;
            } & MarkInternalLink)
        >;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | ({
        _key: string;
      } & ComplexImage)
    | ({
        _key: string;
      } & Separator)
  >;
};

export type AnalyticsSettings = {
  _type: 'analyticsSettings';
  enabled?: boolean;
  provider?: 'plausible';
  domain?: string;
};

export type MetaSettings = {
  _type: 'metaSettings';
  siteTitle?: string;
  titleTemplate?: string;
  defaultDescription?: string;
  defaultKeywords?: Array<string>;
  defaultOgImage?: ComplexImage;
};

export type SocialLink = {
  _type: 'socialLink';
  platform?:
    | 'facebook'
    | 'instagram'
    | 'twitter'
    | 'linkedin'
    | 'youtube'
    | 'tiktok'
    | 'pinterest'
    | 'snapchat'
    | 'whatsapp'
    | 'telegram'
    | 'other';
  url?: string;
};

export type CtaLink = {
  _type: 'ctaLink';
  type?: 'internal' | 'external';
  label?: string;
  internalLink?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'page';
  };
  externalLink?: MarkExternalLink;
};

export type NavLink = {
  _type: 'navLink';
  type?: 'internal' | 'external';
  title?: string;
  reference?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'page';
  };
  externalLink?: MarkExternalLink;
};

export type RichText = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'normal' | 'h1' | 'h2' | 'h3';
      listItem?: 'bullet' | 'number';
      markDefs?: Array<
        | ({
            _key: string;
          } & MarkExternalLink)
        | ({
            _key: string;
          } & MarkInternalLink)
      >;
      level?: number;
      _type: 'block';
      _key: string;
    }
  | ({
      _key: string;
    } & ComplexImage)
  | ({
      _key: string;
    } & Separator)
>;

export type MarkInternalLink = {
  _type: 'markInternalLink';
  link?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'page';
  };
};

export type Page = {
  _id: string;
  _type: 'page';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  meta?: Meta;
  contentMode?: 'richText' | 'pageBuilder';
  richText?: RichText;
  components?: Array<
    {
      _key: string;
    } & PageBuilderComponent
  >;
};

export type MarkExternalLink = {
  _type: 'markExternalLink';
  type?: 'url' | 'email' | 'phone' | 'file';
  url?: string;
  email?: string;
  phone?: string;
  file?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
    };
    media?: unknown;
    _type: 'file';
  };
};

export type Separator = {
  _type: 'separator';
  info?: string;
};

export type Meta = {
  _type: 'meta';
  title?: string;
  description?: string;
  keywords?: Array<string>;
  ogImage?: ComplexImage;
  visibility?: 'public' | 'hidden' | 'private';
};

export type ComplexImage = {
  _type: 'complexImage';
  asset?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  alt?: string;
  caption?: string;
  width?: number;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes =
  | Footer
  | Header
  | ThemeSettings
  | SiteSettings
  | PageBuilderComponent
  | AnalyticsSettings
  | MetaSettings
  | SocialLink
  | CtaLink
  | NavLink
  | RichText
  | MarkInternalLink
  | Page
  | MarkExternalLink
  | Separator
  | Meta
  | ComplexImage
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageMetadata
  | Geopoint
  | Slug
  | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./app/sanity/queries/analytics.ts
// Variable: ANALYTICS_QUERY
// Query: *[_type == "siteSettings"][0]{    analytics{      enabled,      provider,      domain    }  }
export type ANALYTICS_QUERYResult = {
  analytics: {
    enabled: boolean | null;
    provider: 'plausible' | null;
    domain: string | null;
  } | null;
} | null;

// Source: ./app/sanity/queries/footer.ts
// Variable: FOOTER_QUERY
// Query: *[_type == "footer"][0]{    _id,    _type,    logo{      alt,      caption,      width,      crop,      hotspot,      asset->{        _id,        url,        metadata{          dimensions{width, height, aspectRatio},          lqip        }      }    },    mainNav[]{      type,      title,      reference->{        _id,        _type,        slug      },      externalLink{        type,        url,        email,        phone,        "fileUrl": file.asset->url      }    },    secondaryNav[]{      type,      title,      reference->{        _id,        _type,        slug      },      externalLink{        type,        url,        email,        phone,        "fileUrl": file.asset->url      }    },    socials[]{platform, url}  }
export type FOOTER_QUERYResult = {
  _id: string;
  _type: 'footer';
  logo: {
    alt: string | null;
    caption: string | null;
    width: number | null;
    crop: null;
    hotspot: null;
    asset: null;
  } | null;
  mainNav: Array<{
    type: 'external' | 'internal' | null;
    title: string | null;
    reference: {
      _id: string;
      _type: 'page';
      slug: Slug | null;
    } | null;
    externalLink: {
      type: 'email' | 'file' | 'phone' | 'url' | null;
      url: string | null;
      email: string | null;
      phone: string | null;
      fileUrl: string | null;
    } | null;
  }> | null;
  secondaryNav: Array<{
    type: 'external' | 'internal' | null;
    title: string | null;
    reference: {
      _id: string;
      _type: 'page';
      slug: Slug | null;
    } | null;
    externalLink: {
      type: 'email' | 'file' | 'phone' | 'url' | null;
      url: string | null;
      email: string | null;
      phone: string | null;
      fileUrl: string | null;
    } | null;
  }> | null;
  socials: Array<{
    platform:
      | 'facebook'
      | 'instagram'
      | 'linkedin'
      | 'other'
      | 'pinterest'
      | 'snapchat'
      | 'telegram'
      | 'tiktok'
      | 'twitter'
      | 'whatsapp'
      | 'youtube'
      | null;
    url: string | null;
  }> | null;
} | null;

// Source: ./app/sanity/queries/header.ts
// Variable: HEADER_QUERY
// Query: *[_type == "header"][0]{    _id,    _type,    logo{      alt,      caption,      width,      crop,      hotspot,      asset->{        _id,        url,        metadata{          dimensions{width, height, aspectRatio},          lqip        }      }    },    nav[]{      type,      title,      reference->{        _id,        _type,        slug      },      externalLink{        type,        url,        email,        phone,        "fileUrl": file.asset->url      }    }  }
export type HEADER_QUERYResult = {
  _id: string;
  _type: 'header';
  logo: {
    alt: string | null;
    caption: string | null;
    width: number | null;
    crop: null;
    hotspot: null;
    asset: null;
  } | null;
  nav: Array<{
    type: 'external' | 'internal' | null;
    title: string | null;
    reference: {
      _id: string;
      _type: 'page';
      slug: Slug | null;
    } | null;
    externalLink: {
      type: 'email' | 'file' | 'phone' | 'url' | null;
      url: string | null;
      email: string | null;
      phone: string | null;
      fileUrl: string | null;
    } | null;
  }> | null;
} | null;

// Source: ./app/sanity/queries/homepage.ts
// Variable: HOMEPAGE_QUERY
// Query: *[_type == "page" && _id == "homepage"][0]{    _id,    _type,    title,    slug,    meta{      title,      description,      keywords,      ogImage{        alt,        caption,        width,        crop,        hotspot,        asset->{          _id,          url,          metadata{            dimensions{width, height, aspectRatio},            lqip          }        }      },      visibility    },    contentMode,    richText[]{      ...,      markDefs[]{        ...,        link->{          _id,          _type,          slug        }      }    },    components[]{      title,      body[]{        ...,        markDefs[]{          ...,          link->{            _id,            _type,            slug          }        }      }    }  }
export type HOMEPAGE_QUERYResult = {
  _id: string;
  _type: 'page';
  title: string | null;
  slug: Slug | null;
  meta: {
    title: string | null;
    description: string | null;
    keywords: Array<string> | null;
    ogImage: {
      alt: string | null;
      caption: string | null;
      width: number | null;
      crop: null;
      hotspot: null;
      asset: null;
    } | null;
    visibility: 'hidden' | 'private' | 'public' | null;
  } | null;
  contentMode: 'pageBuilder' | 'richText' | null;
  richText: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'h1' | 'h2' | 'h3' | 'normal';
        listItem?: 'bullet' | 'number';
        markDefs: Array<
          | {
              _key: string;
              _type: 'markExternalLink';
              type?: 'email' | 'file' | 'phone' | 'url';
              url?: string;
              email?: string;
              phone?: string;
              file?: {
                asset?: {
                  _ref: string;
                  _type: 'reference';
                  _weak?: boolean;
                  [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
                };
                media?: unknown;
                _type: 'file';
              };
              link: null;
            }
          | {
              _key: string;
              _type: 'markInternalLink';
              link: {
                _id: string;
                _type: 'page';
                slug: Slug | null;
              } | null;
            }
        > | null;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | {
        _key: string;
        _type: 'complexImage';
        asset?: {
          asset?: {
            _ref: string;
            _type: 'reference';
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
          };
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: 'image';
        };
        alt?: string;
        caption?: string;
        width?: number;
        markDefs: null;
      }
    | {
        _key: string;
        _type: 'separator';
        info?: string;
        markDefs: null;
      }
  > | null;
  components: Array<{
    title: string | null;
    body: Array<
      | {
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: 'span';
            _key: string;
          }>;
          style?: 'h1' | 'h2' | 'h3' | 'normal';
          listItem?: 'bullet' | 'number';
          markDefs: Array<
            | {
                _key: string;
                _type: 'markExternalLink';
                type?: 'email' | 'file' | 'phone' | 'url';
                url?: string;
                email?: string;
                phone?: string;
                file?: {
                  asset?: {
                    _ref: string;
                    _type: 'reference';
                    _weak?: boolean;
                    [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
                  };
                  media?: unknown;
                  _type: 'file';
                };
                link: null;
              }
            | {
                _key: string;
                _type: 'markInternalLink';
                link: {
                  _id: string;
                  _type: 'page';
                  slug: Slug | null;
                } | null;
              }
          > | null;
          level?: number;
          _type: 'block';
          _key: string;
        }
      | {
          _key: string;
          _type: 'complexImage';
          asset?: {
            asset?: {
              _ref: string;
              _type: 'reference';
              _weak?: boolean;
              [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
            };
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            _type: 'image';
          };
          alt?: string;
          caption?: string;
          width?: number;
          markDefs: null;
        }
      | {
          _key: string;
          _type: 'separator';
          info?: string;
          markDefs: null;
        }
    > | null;
  }> | null;
} | null;

// Source: ./app/sanity/queries/page.ts
// Variable: PAGE_QUERY
// Query: *[_type == "page" && slug.current == $slug][0]{    _id,    _type,    title,    slug,    meta{      title,      description,      keywords,      ogImage{        alt,        caption,        width,        crop,        hotspot,        asset->{          _id,          url,          metadata{            dimensions{width, height, aspectRatio},            lqip          }        }      },      visibility    },    contentMode,    richText[]{      ...,      markDefs[]{        ...,        link->{          _id,          _type,          slug        }      }    },    components[]{      title,      body[]{        ...,        markDefs[]{          ...,          link->{            _id,            _type,            slug          }        }      }    }  }
export type PAGE_QUERYResult = {
  _id: string;
  _type: 'page';
  title: string | null;
  slug: Slug | null;
  meta: {
    title: string | null;
    description: string | null;
    keywords: Array<string> | null;
    ogImage: {
      alt: string | null;
      caption: string | null;
      width: number | null;
      crop: null;
      hotspot: null;
      asset: null;
    } | null;
    visibility: 'hidden' | 'private' | 'public' | null;
  } | null;
  contentMode: 'pageBuilder' | 'richText' | null;
  richText: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'h1' | 'h2' | 'h3' | 'normal';
        listItem?: 'bullet' | 'number';
        markDefs: Array<
          | {
              _key: string;
              _type: 'markExternalLink';
              type?: 'email' | 'file' | 'phone' | 'url';
              url?: string;
              email?: string;
              phone?: string;
              file?: {
                asset?: {
                  _ref: string;
                  _type: 'reference';
                  _weak?: boolean;
                  [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
                };
                media?: unknown;
                _type: 'file';
              };
              link: null;
            }
          | {
              _key: string;
              _type: 'markInternalLink';
              link: {
                _id: string;
                _type: 'page';
                slug: Slug | null;
              } | null;
            }
        > | null;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | {
        _key: string;
        _type: 'complexImage';
        asset?: {
          asset?: {
            _ref: string;
            _type: 'reference';
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
          };
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: 'image';
        };
        alt?: string;
        caption?: string;
        width?: number;
        markDefs: null;
      }
    | {
        _key: string;
        _type: 'separator';
        info?: string;
        markDefs: null;
      }
  > | null;
  components: Array<{
    title: string | null;
    body: Array<
      | {
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: 'span';
            _key: string;
          }>;
          style?: 'h1' | 'h2' | 'h3' | 'normal';
          listItem?: 'bullet' | 'number';
          markDefs: Array<
            | {
                _key: string;
                _type: 'markExternalLink';
                type?: 'email' | 'file' | 'phone' | 'url';
                url?: string;
                email?: string;
                phone?: string;
                file?: {
                  asset?: {
                    _ref: string;
                    _type: 'reference';
                    _weak?: boolean;
                    [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
                  };
                  media?: unknown;
                  _type: 'file';
                };
                link: null;
              }
            | {
                _key: string;
                _type: 'markInternalLink';
                link: {
                  _id: string;
                  _type: 'page';
                  slug: Slug | null;
                } | null;
              }
          > | null;
          level?: number;
          _type: 'block';
          _key: string;
        }
      | {
          _key: string;
          _type: 'complexImage';
          asset?: {
            asset?: {
              _ref: string;
              _type: 'reference';
              _weak?: boolean;
              [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
            };
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            _type: 'image';
          };
          alt?: string;
          caption?: string;
          width?: number;
          markDefs: null;
        }
      | {
          _key: string;
          _type: 'separator';
          info?: string;
          markDefs: null;
        }
    > | null;
  }> | null;
} | null;

// Source: ./app/sanity/queries/site-settings.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{    _id,    _type,    metaSettings{      siteTitle,      titleTemplate,      defaultDescription,      defaultKeywords,      defaultOgImage{  alt,  caption,  width,  crop,  hotspot,  asset->{    _id,    url,    metadata{      dimensions{width, height, aspectRatio},      lqip    }  }}    },    favicon{      ...,      asset->{_id, url}    },    ogVisual{  alt,  caption,  width,  crop,  hotspot,  asset->{    _id,    url,    metadata{      dimensions{width, height, aspectRatio},      lqip    }  }},    socials[]{platform, url},    privacyPolicy->{_id, _type, title, slug, meta{visibility}},    imprint->{_id, _type, title, slug, meta{visibility}},    analytics{      enabled,      provider,      domain    }  }
export type SITE_SETTINGS_QUERYResult = {
  _id: string;
  _type: 'siteSettings';
  metaSettings: {
    siteTitle: string | null;
    titleTemplate: string | null;
    defaultDescription: string | null;
    defaultKeywords: Array<string> | null;
    defaultOgImage: {
      alt: string | null;
      caption: string | null;
      width: number | null;
      crop: null;
      hotspot: null;
      asset: null;
    } | null;
  } | null;
  favicon: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  } | null;
  ogVisual: {
    alt: string | null;
    caption: string | null;
    width: number | null;
    crop: null;
    hotspot: null;
    asset: null;
  } | null;
  socials: Array<{
    platform:
      | 'facebook'
      | 'instagram'
      | 'linkedin'
      | 'other'
      | 'pinterest'
      | 'snapchat'
      | 'telegram'
      | 'tiktok'
      | 'twitter'
      | 'whatsapp'
      | 'youtube'
      | null;
    url: string | null;
  }> | null;
  privacyPolicy: {
    _id: string;
    _type: 'page';
    title: string | null;
    slug: Slug | null;
    meta: {
      visibility: 'hidden' | 'private' | 'public' | null;
    } | null;
  } | null;
  imprint: {
    _id: string;
    _type: 'page';
    title: string | null;
    slug: Slug | null;
    meta: {
      visibility: 'hidden' | 'private' | 'public' | null;
    } | null;
  } | null;
  analytics: {
    enabled: boolean | null;
    provider: 'plausible' | null;
    domain: string | null;
  } | null;
} | null;

// Source: ./app/sanity/queries/sitemap.ts
// Variable: SITEMAP_QUERY
// Query: *[    _type == "page" &&    (meta.visibility == "public" || !defined(meta.visibility))  ]{    "url": select(      _id == "homepage" => "/",      defined(slug.current) => "/" + slug.current,      null    ),    _updatedAt  }[defined(url)]
export type SITEMAP_QUERYResult = Array<{
  url: string | '/' | null;
  _updatedAt: string;
}>;

// Source: ./app/sanity/queries/theme-settings.ts
// Variable: THEME_SETTINGS_QUERY
// Query: *[_type == "themeSettings"][0]{    _id,    _type,    brandColor,    textColor,    backgroundColor  }
export type THEME_SETTINGS_QUERYResult = {
  _id: string;
  _type: 'themeSettings';
  brandColor: string | null;
  textColor: string | null;
  backgroundColor: string | null;
} | null;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[_type == "siteSettings"][0]{\n    analytics{\n      enabled,\n      provider,\n      domain\n    }\n  }\n': ANALYTICS_QUERYResult;
    '\n  *[_type == "footer"][0]{\n    _id,\n    _type,\n    logo{\n      alt,\n      caption,\n      width,\n      crop,\n      hotspot,\n      asset->{\n        _id,\n        url,\n        metadata{\n          dimensions{width, height, aspectRatio},\n          lqip\n        }\n      }\n    },\n    mainNav[]{\n      type,\n      title,\n      reference->{\n        _id,\n        _type,\n        slug\n      },\n      externalLink{\n        type,\n        url,\n        email,\n        phone,\n        "fileUrl": file.asset->url\n      }\n    },\n    secondaryNav[]{\n      type,\n      title,\n      reference->{\n        _id,\n        _type,\n        slug\n      },\n      externalLink{\n        type,\n        url,\n        email,\n        phone,\n        "fileUrl": file.asset->url\n      }\n    },\n    socials[]{platform, url}\n  }\n': FOOTER_QUERYResult;
    '\n  *[_type == "header"][0]{\n    _id,\n    _type,\n    logo{\n      alt,\n      caption,\n      width,\n      crop,\n      hotspot,\n      asset->{\n        _id,\n        url,\n        metadata{\n          dimensions{width, height, aspectRatio},\n          lqip\n        }\n      }\n    },\n    nav[]{\n      type,\n      title,\n      reference->{\n        _id,\n        _type,\n        slug\n      },\n      externalLink{\n        type,\n        url,\n        email,\n        phone,\n        "fileUrl": file.asset->url\n      }\n    }\n  }\n': HEADER_QUERYResult;
    '\n  *[_type == "page" && _id == "homepage"][0]{\n    _id,\n    _type,\n    title,\n    slug,\n    meta{\n      title,\n      description,\n      keywords,\n      ogImage{\n        alt,\n        caption,\n        width,\n        crop,\n        hotspot,\n        asset->{\n          _id,\n          url,\n          metadata{\n            dimensions{width, height, aspectRatio},\n            lqip\n          }\n        }\n      },\n      visibility\n    },\n    contentMode,\n    richText[]{\n      ...,\n      markDefs[]{\n        ...,\n        link->{\n          _id,\n          _type,\n          slug\n        }\n      }\n    },\n    components[]{\n      title,\n      body[]{\n        ...,\n        markDefs[]{\n          ...,\n          link->{\n            _id,\n            _type,\n            slug\n          }\n        }\n      }\n    }\n  }\n': HOMEPAGE_QUERYResult;
    '\n  *[_type == "page" && slug.current == $slug][0]{\n    _id,\n    _type,\n    title,\n    slug,\n    meta{\n      title,\n      description,\n      keywords,\n      ogImage{\n        alt,\n        caption,\n        width,\n        crop,\n        hotspot,\n        asset->{\n          _id,\n          url,\n          metadata{\n            dimensions{width, height, aspectRatio},\n            lqip\n          }\n        }\n      },\n      visibility\n    },\n    contentMode,\n    richText[]{\n      ...,\n      markDefs[]{\n        ...,\n        link->{\n          _id,\n          _type,\n          slug\n        }\n      }\n    },\n    components[]{\n      title,\n      body[]{\n        ...,\n        markDefs[]{\n          ...,\n          link->{\n            _id,\n            _type,\n            slug\n          }\n        }\n      }\n    }\n  }\n': PAGE_QUERYResult;
    '\n  *[_type == "siteSettings"][0]{\n    _id,\n    _type,\n    metaSettings{\n      siteTitle,\n      titleTemplate,\n      defaultDescription,\n      defaultKeywords,\n      defaultOgImage{\n  alt,\n  caption,\n  width,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata{\n      dimensions{width, height, aspectRatio},\n      lqip\n    }\n  }\n}\n    },\n    favicon{\n      ...,\n      asset->{_id, url}\n    },\n    ogVisual{\n  alt,\n  caption,\n  width,\n  crop,\n  hotspot,\n  asset->{\n    _id,\n    url,\n    metadata{\n      dimensions{width, height, aspectRatio},\n      lqip\n    }\n  }\n},\n    socials[]{platform, url},\n    privacyPolicy->{_id, _type, title, slug, meta{visibility}},\n    imprint->{_id, _type, title, slug, meta{visibility}},\n    analytics{\n      enabled,\n      provider,\n      domain\n    }\n  }\n': SITE_SETTINGS_QUERYResult;
    '\n  *[\n    _type == "page" &&\n    (meta.visibility == "public" || !defined(meta.visibility))\n  ]{\n    "url": select(\n      _id == "homepage" => "/",\n      defined(slug.current) => "/" + slug.current,\n      null\n    ),\n    _updatedAt\n  }[defined(url)]\n': SITEMAP_QUERYResult;
    '\n  *[_type == "themeSettings"][0]{\n    _id,\n    _type,\n    brandColor,\n    textColor,\n    backgroundColor\n  }\n': THEME_SETTINGS_QUERYResult;
  }
}
