/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 4a7530e35a9bfdcc6042382fa6b15d69)
interface __BaseEnv_Env {
	SITE_URL: "https://your-domain.example";
	PRODUCTION_URL: "https://your-domain.example";
	VITE_SANITY_PROJECT_ID: string;
	VITE_SANITY_DATASET: string;
	VITE_SANITY_API_VERSION: string;
	VITE_SANITY_STUDIO_URL: string;
	VITE_SANITY_STUDIO_PREVIEW_ORIGIN: string;
	SANITY_READ_TOKEN: string;
	SANITY_SESSION_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./workers/app");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SITE_URL" | "PRODUCTION_URL" | "VITE_SANITY_PROJECT_ID" | "VITE_SANITY_DATASET" | "VITE_SANITY_API_VERSION" | "VITE_SANITY_STUDIO_URL" | "VITE_SANITY_STUDIO_PREVIEW_ORIGIN" | "SANITY_READ_TOKEN" | "SANITY_SESSION_SECRET">> {}
}
