// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/house/:id": {
    params: {
      "id": string;
    };
  };
  "/api/preview-mode/enable": {
    params: {};
  };
  "/api/preview-mode/disable": {
    params: {};
  };
  "/studio": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/house/:id" | "/api/preview-mode/enable" | "/api/preview-mode/disable" | "/studio";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/house.$id.tsx": {
    id: "routes/house.$id";
    page: "/house/:id";
  };
  "routes/api/preview-mode/enable.ts": {
    id: "routes/api/preview-mode/enable";
    page: "/api/preview-mode/enable";
  };
  "routes/api/preview-mode/disable.ts": {
    id: "routes/api/preview-mode/disable";
    page: "/api/preview-mode/disable";
  };
  "routes/studio.$.tsx": {
    id: "routes/studio.$";
    page: "/studio";
  };
};